### ISSUE TITLE
Eror build naiveproxy openwrt 19.07.4

### ISSUE THREAD

**Issue by predators46** [immortalwrt/openwrt-naiveproxy#8]
`  ERROR at //build/util/version.gni:73:11 (//build/toolchain/linux:clang_x64): Could not execute interpreter.
_result = exec_script("version.py",
          ^----------
I was trying to execute "/home/ubuntu/uu/staging_dir/hostpkg/bin/python3".
See //ui/gl/features.gni:8:1: whence it was imported.
import("//build/util/version.gni")
^--------------------------------
See //gpu/command_buffer/client/BUILD.gn:5:1: whence it was imported.
import("//ui/gl/features.gni")
^----------------------------
See //third_party/blink/renderer/platform/BUILD.gn:152:5: which caused the file to be included.
    "//gpu/command_buffer/client:client",
    ^-----------------------------------
ninja: Entering directory `out/Release'
ninja: error: loading 'build.ninja': No such file or directory
Makefile:148: recipe for target '/home/ubuntu/uu/build_dir/target-mipsel_24kc_musl/naiveproxy-89.0.4389.72-1/.built' failed
make[2]: *** [/home/ubuntu/uu/build_dir/target-mipsel_24kc_musl/naiveproxy-89.0.4389.72-1/.built] Error 1   `

**Comment by 1715173329** [comment]
I have no plan to support 19.07, maybe you can do it yourself.
